site_name: SilkGameCore 
site_url: https://leanosuna.github.io/SilkGameCore/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode    
      primary: teal
      accent: lime

    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
      primary: teal
      accent: purple 
plugins:
  # - social
  - search

nav:
  - Home: index.md
  # - Getting Started: getting-started.md
  # - API: api.md